#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Dec 29 15:52:47 +0100 2023
# SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_5 processing_system7_vip_v1_0_7 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_19 fifo_generator_v13_2_4 axi_data_fifo_v2_1_18 axi_crossbar_v2_1_20 xlconcat_v2_1_3 xbip_utils_v3_0_10 c_reg_fd_v12_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_6 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_13 c_gate_bit_v12_0_6 xbip_counter_v3_0_6 c_counter_binary_v12_0_13 c_mux_bit_v12_0_6 c_shift_ram_v12_0_13 register_array_v1_00_a util_reduced_logic_v2_0_4 lib_pkg_v1_0_2 lib_fifo_v1_0_13 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_21 axi_sg_v4_1_12 axi_dma_v7_1_20 xlconstant_v1_1_6 smartconnect_v1_0 util_vector_logic_v2_0_1 xlslice_v1_0_2 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_21 axis_infrastructure_v1_1_0 axis_data_fifo_v2_0_1 xbip_bram18k_v3_0_6 mult_gen_v12_0_15 pulse_width_modulator_v1_00_a axi_timer_v2_0_21 axi_protocol_converter_v2_1_19)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2019.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/d4a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps7_0_100M_0/sim/design_1_rst_ps7_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/4d88/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1f5a/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_4 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/5b9c/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ace7/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Aurora_status_concat_0_0/sim/design_1_Aurora_status_concat_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Aurora_status_concat_1_0/sim/design_1_Aurora_status_concat_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1123/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/edec/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/cfdd/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_13 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/cbe4/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/7161/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/9ac8/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_13 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/23f1/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_c_counter_binary_0_0/sim/design_1_c_counter_binary_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ecb4/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_13 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/cd8a/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_capture_pwm_base1_0/sim/design_1_capture_pwm_base1_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_capture_rx0_0/sim/design_1_capture_rx0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_capture_timer_int_0/sim/design_1_capture_timer_int_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ipshared/47a6/rtl/drp_bridge.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_drp_bridge_0_0/sim/design_1_drp_bridge_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work register_array_v1_00_a $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ac34/hdl/vhdl/user_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ac34/hdl/vhdl/register_array_axi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_gigabit_regarray_0/sim/design_1_gigabit_regarray_0.vhd" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/06c8/hdl/vhdl/internal_reset_timer.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_internal_reset_timer_aurora0_0/sim/design_1_internal_reset_timer_aurora0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_internal_reset_timer_aurora_gt_0_0/sim/design_1_internal_reset_timer_aurora_gt_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work util_reduced_logic_v2_0_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/4c94/hdl/util_reduced_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_intr_ce_type_joint_0_0/sim/design_1_intr_ce_type_joint_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_aurora_pkg.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_reset_logic.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0_core.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_support.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_gt_common_wrapper.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_support_reset_logic.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_clock_module.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_aurora_lane_4byte.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_axi_to_ll.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_channel_err_detect.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_channel_init_sm.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_chbond_count_dec_4byte.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_crc_top.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_err_detect_4byte.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_global_logic.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_hotplug.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_idle_and_ver_gen.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_lane_init_sm_4byte.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_left_align_control.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_left_align_mux.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_ll_to_axi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_output_mux.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_output_switch_control.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_rx_ll_deframer.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_rx_ll_pdu_datapath.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_rx_ll.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_rxcrc.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_sideband_output.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_standard_cc_module.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_storage_ce_control.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_storage_count_control.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_storage_mux.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_storage_switch_control.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_sym_dec_4byte.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_sym_gen_4byte.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_cdc_sync.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/gt/design_1_aurora_8b10b_0_0_tx_startup_fsm.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/gt/design_1_aurora_8b10b_0_0_rx_startup_fsm.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/gt/design_1_aurora_8b10b_0_0_gt.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/gt/design_1_aurora_8b10b_0_0_multi_gt.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/gt/design_1_aurora_8b10b_0_0_transceiver_wrapper.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_tx_ll_control.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_tx_ll_datapath.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_tx_ll.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_txcrc.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0/src/design_1_aurora_8b10b_0_0_valid_data_counter.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_0_0/design_1_aurora_8b10b_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_aurora_pkg.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_reset_logic.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0_core.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_aurora_lane_4byte.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_axi_to_ll.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_channel_err_detect.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_channel_init_sm.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_chbond_count_dec_4byte.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_crc_top.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_err_detect_4byte.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_global_logic.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_hotplug.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_idle_and_ver_gen.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_lane_init_sm_4byte.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_left_align_control.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_left_align_mux.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_ll_to_axi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_output_mux.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_output_switch_control.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_rx_ll_deframer.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_rx_ll_pdu_datapath.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_rx_ll.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_rxcrc.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_sideband_output.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_standard_cc_module.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_storage_ce_control.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_storage_count_control.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_storage_mux.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_storage_switch_control.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_sym_dec_4byte.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_sym_gen_4byte.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_cdc_sync.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/gt/design_1_aurora_8b10b_1_0_tx_startup_fsm.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/gt/design_1_aurora_8b10b_1_0_rx_startup_fsm.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/gt/design_1_aurora_8b10b_1_0_gt.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/gt/design_1_aurora_8b10b_1_0_multi_gt.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/gt/design_1_aurora_8b10b_1_0_transceiver_wrapper.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_tx_ll_control.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_tx_ll_datapath.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_tx_ll.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_txcrc.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0/src/design_1_aurora_8b10b_1_0_valid_data_counter.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_8b10b_1_0/design_1_aurora_8b10b_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/4dac/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_21 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/e644/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_12 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/91f3/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_20 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/260a/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_dma_0_0/sim/design_1_axi_dma_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/c796/hdl/axi_s_sync_frame_detector.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/c796/hdl/axi_register_array.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/c796/hdl/axi_s_frame_simplex_switch.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/c796/hdl/axi_s_chain_link_switch.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_s_chain_link_swi_0_0/sim/design_1_axi_s_chain_link_swi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/sim/bd_afc3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/66e7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/sim/bd_afc3_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/sim/bd_afc3_psr0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/sim/bd_afc3_psr_aclk_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/sim/bd_afc3_psr_aclk1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/sim/bd_afc3_arsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/sim/bd_afc3_rsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/sim/bd_afc3_awsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/sim/bd_afc3_wsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/sim/bd_afc3_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/f85e/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/sim/bd_afc3_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ca72/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/sim/bd_afc3_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/7de4/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/sim/bd_afc3_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/sim/bd_afc3_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_13/sim/bd_afc3_sarn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_14/sim/bd_afc3_srn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_15/sim/bd_afc3_sawn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/sim/bd_afc3_swn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_17/sim/bd_afc3_sbn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_18/sim/bd_afc3_s01mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_19/sim/bd_afc3_s01tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/sim/bd_afc3_s01sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/sim/bd_afc3_s01a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_22/sim/bd_afc3_sarn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/sim/bd_afc3_srn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/sim/bd_afc3_s02mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/sim/bd_afc3_s02tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_26/sim/bd_afc3_s02sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_27/sim/bd_afc3_s02a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_28/sim/bd_afc3_sawn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_29/sim/bd_afc3_swn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_30/sim/bd_afc3_sbn_1.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_31/sim/bd_afc3_m00s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_32/sim/bd_afc3_m00arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_33/sim/bd_afc3_m00rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/sim/bd_afc3_m00awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_35/sim/bd_afc3_m00wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/sim/bd_afc3_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b387/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/sim/bd_afc3_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_0/sim/design_1_axi_smc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_channel_up_n_0_0/sim/design_1_channel_up_n_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_channel_up_n_1_0/sim/design_1_channel_up_n_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_rx_lpm_en0_0/sim/design_1_rx_lpm_en0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_rx_lpm_en1_0/sim/design_1_rx_lpm_en1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_sys_reset_n_0_0/sim/design_1_sys_reset_n_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_tvalid_0/sim/design_1_tvalid_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_stuff_16_0_0_0/sim/design_1_stuff_16_0_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_stuff_32_0_1_0/sim/design_1_stuff_32_0_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_stuff_6_0_0_0/sim/design_1_stuff_6_0_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_synchronizer_reg_1_0/sim/design_1_synchronizer_reg_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/f044/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_0_0_0/sim/design_1_xlslice_0_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_1_1_0/sim/design_1_xlslice_1_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_capture_rx0_1/sim/design_1_capture_rx0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_0_4/sim/design_1_xlconcat_0_4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_aurora_0_status_0/sim/design_1_xlconcat_aurora_0_status_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_0/sim/design_1_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_21 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/9c6e/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_0_0/sim/design_1_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_dma_0_1/sim/design_1_axi_dma_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/e1b1/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_data_fifo_0_0/sim/design_1_axis_data_fifo_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/sim/bd_48ac.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_48ac_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_48ac_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_48ac_arsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_48ac_rsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_48ac_awsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_48ac_wsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_48ac_bsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_48ac_s00mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_48ac_s00tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_48ac_s00sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_48ac_s00a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_48ac_sarn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_48ac_srn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_48ac_sawn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_48ac_swn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_48ac_sbn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_48ac_s01mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_48ac_s01tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_48ac_s01sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_48ac_s01a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_48ac_sarn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_48ac_srn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_48ac_s02mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_48ac_s02tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_48ac_s02sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_48ac_s02a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_48ac_sawn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_48ac_swn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_48ac_sbn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_48ac_m00s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_48ac_m00arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_48ac_m00rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_48ac_m00awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/sim/bd_48ac_m00wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_34/sim/bd_48ac_m00bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/sim/bd_48ac_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/sim/design_1_smartconnect_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_0/emu_dc_c_addsub_v12_0_i0/sim/emu_dc_c_addsub_v12_0_i0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_0/emu_dc_c_addsub_v12_0_i1/sim/emu_dc_c_addsub_v12_0_i1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_0/emu_dc_c_addsub_v12_0_i2/sim/emu_dc_c_addsub_v12_0_i2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_0/emu_dc_c_addsub_v12_0_i3/sim/emu_dc_c_addsub_v12_0_i3.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_0/emu_dc_c_counter_binary_v12_0_i0/sim/emu_dc_c_counter_binary_v12_0_i0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_emu_dc_0_0/emu_dc_mult_gen_v12_0_i0/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_15 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_emu_dc_0_0/emu_dc_mult_gen_v12_0_i0/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_0/emu_dc_mult_gen_v12_0_i0/sim/emu_dc_mult_gen_v12_0_i0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_0/emu_dc_mult_gen_v12_0_i1/sim/emu_dc_mult_gen_v12_0_i1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_0/emu_dc_mult_gen_v12_0_i2/sim/emu_dc_mult_gen_v12_0_i2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_0/emu_dc_mult_gen_v12_0_i3/sim/emu_dc_mult_gen_v12_0_i3.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_0/emu_dc_mult_gen_v12_0_i4/sim/emu_dc_mult_gen_v12_0_i4.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_0/emu_dc_mult_gen_v12_0_i5/sim/emu_dc_mult_gen_v12_0_i5.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_0/emu_dc_mult_gen_v12_0_i6/sim/emu_dc_mult_gen_v12_0_i6.vhd" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl/conv_pkg.vhd" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl/synth_reg.vhd" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl/synth_reg_w_init.vhd" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl/srl17e.vhd" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl/srl33e.vhd" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl/synth_reg_reg.vhd" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl/single_reg_w_init.vhd" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl/xlclockdriver_rd.vhd" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl/emu_dc_entity_declarations.vhd" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl/emu_dc.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl/emu_dc_axi_lite_interface_verilog.v" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl/synth_reg.v" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl/synth_reg_w_init.v" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl/convert_type.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_0/sim/design_1_emu_dc_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_1_0/sim/design_1_xlconstant_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_2_0/sim/design_1_xlconstant_2_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work pulse_width_modulator_v1_00_a $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/c07a/hdl/vhdl/user_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/c07a/hdl/vhdl/pulse_width_modulator_axi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_pulse_width_modulator_0_0/sim/design_1_pulse_width_modulator_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_0_1/sim/design_1_xlslice_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_timer_v2_0_21 $vhdlan_opts \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/a788/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_timer_0_0/sim/design_1_axi_timer_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_0_5/sim/design_1_xlconcat_0_5.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/c83a/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../highspeed_link.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/sim/design_1.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
